name: macos-inst-test

on: [ push ]

permissions:
  contents: read

jobs:
  install-test:
    runs-on: macos-11

  steps:
    - uses: actions/checkout@v3

    - name: Run install script
      run: |
        ./standalone/bash/install.sh beta